"""
This module contains the EfficiencyTask class which iterates over the
lensed lightcurves and computes some quantities useful for calculating
efficiency and quality.
"""
import os
import glob
import pandas as pd
import numpy as np
from microlensing.filtering import (
    lens_filter,
    mahalanobis_distance_ellipse,
    good_detection_filter
)
from pipeline.etl_task import ETLTask

class EfficiencyTask(ETLTask):
    """
    This class reads in lightcurves with synthetic lensing events
    from parquet files and counts how many pass detection criteria,
    how many samples are correctly labeled, and how many times an event
    is "split" by a mislabelled sample.

    Attributes:
        extract_dir (str): Directory containing the input data files to be 
                           processed.
        load_dir (str): Directory where the transformed data files will be 
                        written.
    Methods:
        get_extract_file_path(version, i_tau, bandwidth_type):
            Returns the file_path to process given the version, event duration
            index (i_tau), and bandwidth type..
        get_load_file_path(version, i_tau, bandwidth_type):
            Returns the file_path to load given the version, event duration
            index (i_tau), and bandwidth type..
        transform(data, version, i_tau, bandwidth_type):
            Computes the weighted std per band, rms error per band, and 
            lc_class for each source for given achromaticity version,
            event duration index (i_tau), and bandwidth type..
        run(): 
            Executes the ETL process for each file, applying extract,
            transform, and load sequentially.
    """
    DEFAULT_ITERABLES = [np.arange(0, 49)]

    @staticmethod
    def footprint_area_z_score(df, label_column="cluster_label"):
        """
        Computes the z-score of the footprint area
        using mean and standard deviation of baseline measurements
        """
        m = df[label_column].astype(bool)
        result = (
            (df["footprint_area"] - df.loc[m, "footprint_area"].mean())
            / df.loc[m, "footprint_area"].std()
        )
        return result

    @staticmethod
    def clean_data(data):
        """
        Filters out events that don't include enough bright samples.
        These were generated by accident and would unintentionally
        bias the final result.
        """
        data = data.groupby(
            by=["objectid", "window_number", "filter"],
            as_index=False
        ).filter(lambda x: len(x) > 1)

        data = data.groupby(
            by=["objectid", "window_number", "filter"],
            as_index=False
        ).filter(
            lambda x: x.loc[x["true_label"].astype(bool)].shape[0] > 2
        )
        data = data.groupby(
            by=["objectid", "window_number"],
            as_index=False
        ).filter(
            lambda x: (
                lens_filter(
                    x,
                    min_per_filter=1,
                    n_filters_req=2,
                    label_column="true_label",
                    factor_of_two=False
                )
            )
        )
        result = data.reset_index()
        return result

    def compute_filtering_quantities(self, data):
        """
        Computes the ellipse mahalanobis distance and
        footpring area z-score. Assigns these to new columns
        in the dataframe.
        """
        result = (
            data.groupby(
                by=["objectid", "window_number"],
                as_index=False
            )[data.columns].apply(mahalanobis_distance_ellipse)
        ).reset_index(level=0, drop=True)
        result = result.assign(
            footprint_area=(
                lambda x: (
                    np.pi * x.asemi * x.bsemi
                    * (2.5 * x.kron_radius)**2
                )
            )
        )
        result["footprint_area_z_score"] = result.groupby(
            by=["objectid", "window_number"],
            as_index=False
        ).apply(self.footprint_area_z_score).reset_index(level=0, drop=True)
        return result

    @staticmethod
    def n_filtered(data, filter_func):
        """
        Given a filter_func, this method returns the number of
        groups which pass filter_func (i.e. are not excluded).
        """
        flag_filtered = (
            data.groupby(
                by=["objectid", "window_number"]
            ).filter(filter_func)
        )
        result = flag_filtered.groupby(by=["objectid", "window_number"]).ngroups
        return result

    def transform(self, data, i_tau):
        data = self.clean_data(data)

        if data.empty:
            result = data
            return result

        data = self.compute_filtering_quantities(data)
        first_pass = (
            data
            .groupby(by=["objectid", "window_number"])
            .filter(
                lambda x: (
                    lens_filter(
                        x,
                        min_per_filter=1,
                        n_filters_req=2
                    )
                )
            )
        )

        result_data = {
            "n_events": [
                data.groupby(by=["objectid", "window_number"]).ngroups
            ],
            "n_first_pass": [
                first_pass.groupby(by=["objectid", "window_number"]).ngroups
            ],
            "n_good_det": [
                self.n_filtered(
                    data,
                    good_detection_filter
                )
            ]
        }
        result = pd.DataFrame(
            data=result_data,
            index=[i_tau]
        )
        result.index.name = "duration_index"
        return result

    def run(self, **kwargs):
        """
        Run the task. It accepts the following keyword arguments:
            tau_range: (tuple, optional, default: (0, 48)): A tuple 
                specifying the range of tau indices to process. The first
                element specifies the starting index (inclusive) and the second
                specifies the last (inclusive).
        """
        run_kwargs = {}

        if "tau_range" in kwargs:
            tau_range = kwargs["tau_range"]
            run_kwargs["iterables"] = [np.arange(tau_range[0], tau_range[1]+1)]
        else:
            run_kwargs["iterables"] = self.DEFAULT_ITERABLES

        super().run(**run_kwargs)

    def concat_results(self):
        """
        Concatenate the results from ETL into a single dataframe.
        """
        df_files = glob.glob(f"{self.load_dir}efficiency_results_tau*.parquet")
        dfs = [pd.read_parquet(f) for f in df_files]
        result = pd.concat(dfs, axis=0)
        result.sort_index(inplace=True)
        result.to_parquet(f"{self.load_dir}efficiency_results.parquet")

    def get_extract_file_path(self, i_tau):
        """
        Get the extract file path corresponding to the given
        event duration (specified indirectly by i_tau)
        """
        result = os.path.join(
            self.extract_dir,
            f"lensed_lightcurves_duration{i_tau}.parquet"
        )
        return result

    def get_load_file_path(self, i_tau):
        """
        Get the extract file path corresponding to the given
        event duration (specified indirectly by i_tau).
        """
        result = os.path.join(
            self.load_dir, f"efficiency_results_tau{i_tau}.parquet"
        )
        return result
