data_retrieval:
  batch_size: 100000
  num_batches: 67
  poll_rate: 10

synthetic_events:
  n_events: 100000

scanner:
  v0:
    unique_filters: 2
    samples_per_filter: 1
  v1:
    unique_filters: 3
    samples_per_filter: 1
  v2:
    unique_filters: 3
    samples_per_filter: 2
